In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Dropout
import pandas as pd

from transformer import Transformer

In [2]:
class MyNeuralNet(tf.keras.models.Model):
    def __init__(self, hidden_dim: int, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.nn = Dense(hidden_dim, use_bias=True, activation=tf.nn.relu, name='mynn')
            
    def call(self, input: tf.Tensor):
        out = self.nn(input)        
        return out


In [3]:
vocab_size = 10
hidden_dim = 2
max_len = 5

graph = tf.Graph()
with graph.as_default():
    c = tf.constant([1.0, 2.0])


In [5]:
from sklearn.model_selection import train_test_split
import numpy as np

df = pd.read_csv('tfsample.csv', header=None)
x = df[[0,1]]
y = df[2]
sample = np.array(x)
label = keras.utils.to_categorical(y)

train_x, test_x, train_y, test_y = train_test_split(sample, label, test_size=0.1)

print(train_x)
print(test_x)

[[ 0.55855159  0.52149932]
 [-0.30871248 -0.71048123]
 [-0.33845702 -0.69454539]
 [-0.68846944  0.64366413]
 [-0.83336028  0.5859546 ]
 [-0.79136744 -0.35736276]
 [ 0.87636601  0.44650165]
 [ 0.1476994  -0.95415137]
 [ 0.27438691 -0.9120016 ]
 [-0.57084926  0.96844322]
 [ 0.5010284   0.97587128]
 [ 0.5552638  -0.50094407]
 [-0.74626644  0.16484856]
 [-0.46709891  0.03919218]
 [ 0.44923607 -0.01663816]
 [-0.7206801  -0.65568945]
 [ 0.63912272 -0.03544609]
 [ 0.61395574 -0.93975778]]
[[-0.17923305 -0.22119217]
 [ 0.31327143 -0.45900566]]


In [8]:
mynn = MyNeuralNet(hidden_dim=2)
out = mynn(test_x)
print(out)

tf.Tensor(
[[0.         0.18911701]
 [0.         0.34419265]], shape=(2, 2), dtype=float32)
